name: Conventional Commit Labels

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  label:
    uses: OpenVoiceOS/gh-automations/.github/workflows/conventional-label.yml@82252c363b239fe5c60dc0ae2a4e81721d4cabef
    secrets: inherit
