name: Conventional Commit Labels

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  label:
    uses: OpenVoiceOS/gh-automations/.github/workflows/conventional-label.yml@dev
    secrets: inherit
